"use strict";
exports.__esModule = true;
var Wafer_1 = require("./Wafer");
var APC_1 = require("./APC");
var ProcessTool_1 = require("./ProcessTool");
var ToolCommand_1 = require("./ToolCommand");
var apc = new APC_1.APC();
var processTool_a = new ProcessTool_1.ProcessTool('A');
var processTool_b = new ProcessTool_1.ProcessTool('B');
var wafer1 = new Wafer_1.Wafer('N12345.00', 'Mobile Phone', 'ByProductStrategy', "N3");
var wafer2 = new Wafer_1.Wafer('N54321.00', 'Personal Computer', 'ByProductStrategy', "N5");
var wafer3 = new Wafer_1.Wafer('N11111.00', 'NoteBook', 'ByProductStrategy', "N7");
var wafer4 = new Wafer_1.Wafer('N22222.00', 'Mobile Phone', 'Feedforward', "N3");
var wafer5 = new Wafer_1.Wafer('N33333.00', 'NoteBook', 'Recommend', "N5");
var reticleJob = new ToolCommand_1.ReticleJob('Check-In');
processTool_a.addJobs(reticleJob);
apc.preview(wafer1, processTool_a);
apc.execute(wafer1, processTool_a);
apc.execute(wafer2, processTool_a);
apc.execute(wafer3, processTool_a);
var reticleJob = new ToolCommand_1.ReticleJob('Check-Out');
processTool_a.addJobs(reticleJob);
processTool_a.executeCommand();
