/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HW_5_1;

public class App {

    public static void main(String[] args) {
        
    }

    public String nextDate(int month, int day) {

        if (day == 28) {
            if (month == 2) {
                month++;
                day = 1;
            } else {
                day++;
            }
        }
        else if (day == 30) {
            if (month == 4 || month == 6 || month == 9 || month == 11) {
                month++;
                day = 1;
            } else {
                day++;
            }
        }
        else if (day == 31) {
            if (month == 1 || month == 3 || month == 5 || month == 8 || month == 10) {
                day = 1;
                month++;
            } else if (month == 12) {
                day = 1;
                month = 1;
            }
        }
        else {
            day++;
        }

        return String.format("%02d/%02d", month, day);
    }
}
