/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HW_5_1;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void nextDateAllDUTest() {
        App app = new App();
        assertEquals("03/01", app.nextDate(2, 28));
        assertEquals("01/29", app.nextDate(1, 28));
        assertEquals("05/01", app.nextDate(4, 30));
        assertEquals("01/31", app.nextDate(1, 30));
        assertEquals("02/01", app.nextDate(1, 31));
        assertEquals("01/01", app.nextDate(12, 31));
        assertEquals("01/28", app.nextDate(1, 27));

    }
}
